apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "treetracker-webmap-api"
  namespace: "webmap"
  labels:
    app: "treetracker-webmap-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "treetracker-webmap-api"
  template:
    metadata:
      labels:
        app: "treetracker-webmap-api"
    spec:
      containers:
        - name: "treetracker-webmap-api"
          image: "greenstand/treetracker-webmap-api:1.0.0-latest"
          volumeMounts:
            - name: "configdb-volume"
              mountPath: "/usr/app/server/config/config.js"
              subPath: "config.js"
      volumes:
        - name: "configdb-volume"
          secret:
            secretName: "dbconnection"
